# Generated by Django 3.2 on 2023-03-29 08:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayCondition',
            fields=[
                ('relay_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('time_moment', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.temperaturesensor')),
            ],
        ),
    ]
