# Generated by Django 3.2 on 2023-03-29 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_temperaturehistory_humanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='visitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
