# Generated by Django 4.1.7 on 2023-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_visitor_options_visitor_login_visitor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=32),
        ),
    ]
