# Generated by Django 4.1.7 on 2023-03-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_visitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
