# Generated by Django 3.2 on 2023-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitor_groups_visitor_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='group',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('OPERATOR', 'operator'), ('VISITOR', 'visitor')], default='VISITOR', max_length=32, verbose_name='Группа пользователя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login',
            field=models.CharField(max_length=32, unique=True, verbose_name=' Логин'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=32, verbose_name='Имя'),
        ),
    ]
