# Generated by Django 3.2 on 2023-03-29 19:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230329_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'оплачено'), ('Неоплачено', 'неоплачено')], default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='tariff',
            field=models.FloatField(default=3.16, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
