# Generated by Django 3.2 on 2023-03-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_visitor_group_alter_visitor_login_and_more'),
        ('users', '0006_auto_20230329_1538'),
    ]

    operations = [
    ]
