# Generated by Django 3.2 on 2023-03-29 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='consumed_energy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
