# Generated by Django 3.2 on 2023-03-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20230329_2313'),
        ('users', '0009_visitor_consumed_energy'),
    ]

    operations = [
    ]
