# Generated by Django 3.2 on 2023-03-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_temperaturesensor_visitor_id'),
        ('users', '0009_visitor_consumed_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.temperaturesensor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'оплачено'), ('На оплате', 'на оплате'), ('Неоплачено', 'неоплачено')], default='Неоплачено', max_length=32),
        ),
    ]
