# Generated by Django 3.2 on 2023-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230330_1811'),
        ('users', '0010_merge_20230330_0339'),
    ]

    operations = [
    ]
